version: '2'

services:
  crowd:
    image: asos/crowd
    hostname: crowd
    volumes:
      - /data/atlassian/crowd:/var/atlassian/crowd
    ports:
      - '8095:8095'
    external_links:
      - database/mysql
    environment:
      - "CROWD_PROXY_NAME="
      - "CROWD_PROXY_PORT="
      - "CROWD_PROXY_SCHEME="
      - "CROWD_URL=http://localhost:8095"
      - "LOGIN_BASE_URL=http://localhost:8095"
      - "SPLASH_CONTEXT="
      - "CROWD_CONTEXT=ROOT"
      - "CROWDID_CONTEXT="
      - "OPENID_CLIENT_CONTEXT="
      - "DEMO_CONTEXT="
    labels:
      com.asos.description: "Atlassian Crowd"
      com.asos.service: "crowd"
      io.rancher.scheduler.affinity:host_label: host=atlassian
      io.rancher.container.pull_image: always

